
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/layout/Header";
import Container from "@/app/components/layout/Container";
import MobileUserMenu from "@/app/components/navigation/MobileUserMenu"
import { FilterProvider } from "@/app/context/FilterContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

          <FilterProvider>
            <Header />
            <Container>
              {children}
            </Container>
            <MobileUserMenu />
          </FilterProvider>

      </body>
    </html >
  );
}
